### ISSUE TITLE
[BUG] TypeScript Typings are not supported

### ISSUE THREAD

**Issue by beeman** [khaosdoctor/devto-nodejs-sdk#1] opened 2020-07-02 04:53 UTC
**Describe the bug**

Hey there - first of, thanks for sharing this library!

When using this library in a TypeScript project the module can not be found, resulting in the error below:

```
TS2307: Cannot find module 'devto-nodejs-sdk'.
```

**To Reproduce**
1. Create TypeScript Project
2. yarn add devto-nodejs-sdk
3. import { Client } from 'devto-nodejs-sdk';
4. See error: TS2307: Cannot find module 'devto-nodejs-sdk'.

**Current behavior**
Typings are not exported, module is unknown for TypeScript projects.

**Expected behavior**
Typings should be exported.

**Comment by pablohdev** [comment] 2020-07-02 18:30
Hello I had the same problem. And I saw that from the project sdk the package.json is pointing to the 'dist / index.js' folder, but the folder in the repository doesn't come, I had to run the npm run build in the sdk folder to create it, so I saw that in '.gitignore' this 'dist /' folder is to be ignored.

**Comment by khaosdoctor** [comment] 2020-07-02 22:31
Hey everyone! I'll be looking into it. I'm already taking a look on what might have gone wrong

**Comment by khaosdoctor** [comment] 2020-07-02 23:28
The problem is that I wasn't running the build command like @pablohdev said. I'm testing it right now and it should be good to go in the next version

**Comment by khaosdoctor** [comment] 2020-07-02 23:38
Fixed on the 1.0.4 Release! It should be working fine :)

**Closed by khaosdoctor** 2020-07-02 23:38 UTC
Labels: bug

**Comment by beeman** [comment] 2020-07-03 00:31
Thanks for the quick fix @khaosdoctor, that's really appreciated! 

Going to try it in my app later!

**Comment by pablohdev** [comment] 2020-07-03 01:40
Thanks @khaosdoctor, I am very happy to collaborate and congratulations on this library, it will be very useful.
